# Keybindings

# Lazygit
bind C-g popup -d "#{pane_current_path}" -w 90% -h 70% -E lazygit

# Terminal
bind C-t popup -d "#{pane_current_path}" -w 95% -h 30% -E $SHELL

# Jump to dir
bind C-j popup -d "#{pane_current_path}" -w 95% -h 30% -E ~/.local/bin/tmux-zoxide-cd.sh

# New window with name prompt (centered popup)
bind C new-window -c "#{pane_current_path}" \; display-popup -w 40 -h 3 -E 'read -p "Window name: " name && tmux rename-window "$name"'
